#!/usr/bin/env bash

# Install libraries for Ubuntu.

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

log_start "Install for Ubuntu"

mkdir -p "$HOME/local/bin"

load pkgs/apt/install

# Install Go. https://go.dev/doc/install
GO_ARCHIVE=go1.24.5.linux-amd64.tar.gz
wget https://go.dev/dl/$GO_ARCHIVE
rm -rf /usr/local/go && sudo tar -C /usr/local -xzf $GO_ARCHIVE
rm $GO_ARCHIVE
if [[ ":$PATH:" != *":/usr/local/go/bin:"* ]]; then
    export PATH="$PATH:/usr/local/go/bin"
fi

# XXX: gnome-extensionもやりたい

load lib/rustup

load lang-envs/install

load pkgs/langs/install

if [ ${SHELL##*/} != 'zsh' ]; then
    run ch-sh zsh
fi

log_finish "Install for Ubuntu"
