#!/usr/bin/env bash

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

log_start 'APT get'

install() {
    run sudo apt-get install -y "$@"
}

if ! has 'apt-get'; then
    log_error 'APT is not installed'
    exit 1
else
    run sudo apt-get update

    install git
    install tmux
    install zsh

    # For Ruby compiling
    install libssl-dev
    install libreadline-dev
    install zlib1g-dev
fi

log_finish 'APT get'
