#!/usr/bin/env bash

log_start 'npm install (global)'

install() {
    log_info "Installing node package $(c_magenta $1) ..."
    run npm install -g "$1"
}

if is_dryrun || has npm; then
   install grunt-cli
else
    log_error 'npm is not available'
    exit 1
fi

log_finish 'npm install (global)'
