#!/usr/bin/env bash

VERSIONS=(
    '1.6'
)

for version in ${VERSIONS[@]}; do
    if ! has_version goenv $version; then
        goenv install $version
    fi
done

goenv global ${VERSIONS[0]}

goenv rehash

