#!/usr/bin/env bash

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

ANYENV="$ANYENV_PATH/bin/anyenv"

has_env() {
    local env=$1
    if $ANYENV envs | grep $env >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

has_version() {
    local env=$1
    local version=$2
    if $env versions | grep $version >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

echo 'Install anyenv'

if [ ! -d "$ANYENV_PATH" ]; then
    git clone -b fix-init https://github.com/ryym/anyenv "$ANYENV_PATH"
    eval "$($ANYENV init -)"
fi

for envpath in "$DOTPATH"/sync/env/*env; do
    if ! has_env ${envpath##*/}; then
        $ANYENV install ${envpath##*/}
    fi
done

# Enable each '**env' command.
eval "$($ANYENV init -)"

for envpath in "$DOTPATH"/sync/env/*env; do
    source $envpath
done
