#!/usr/bin/env bash

# Install '**env' tools that can install and manage
# several versions of a language. Currently, we use 'anyenv'
# to manage these '**env' tools.

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

ANYENV="$ANYENV_PATH/bin/anyenv"
source "$DOTPATH/sync/env/helper.sh"

log_start 'Anyenv'

log_info 'Cloning or updating anyenv...'

if [ -d "$ANYENV_PATH" ]; then
  git --work-tree="$ANYENV_PATH" pull | log
else
    git clone -b fix-init https://github.com/ryym/anyenv "$ANYENV_PATH" | log
    eval "$($ANYENV init -)" | log
fi

# Install '**env' tools.
for envpath in "$DOTPATH"/sync/env/*env; do
    if ! has_env ${envpath##*/}; then
        log_info "Install $(c_magenta ${envpath##*/})"
        $ANYENV install ${envpath##*/} | log
    fi
done

# Enable each '**env' command.
eval "$($ANYENV init -)"

# Install languages.
for envpath in "$DOTPATH"/sync/env/*env; do
    source $envpath
done

log_finish 'Anyenv'
