#!/usr/bin/env bash

# Install '**env' tools that can install and manage
# several versions of a language. Currently, we use 'anyenv'
# to manage these '**env' tools.

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

ANYENV="$ANYENV_PATH/bin/anyenv"
source "$DOTPATH/sync/env/helper.sh"

log_start 'Anyenv'

if [ -d "$ANYENV_PATH" ]; then
    run git --work-tree="$ANYENV_PATH" pull
else
    run git clone https://github.com/riywo/anyenv "$ANYENV_PATH"
    run eval "\"\$($ANYENV init -)\""
fi

# Install '**env' tools.
for envpath in "$DOTPATH"/sync/env/*env; do
    if ! has_env ${envpath##*/}; then
        run $ANYENV install "${envpath##*/}"
    fi
done

# Enable each '**env' command.
run eval "\"\$($ANYENV init -)\""

# Install languages.
for envpath in "$DOTPATH"/sync/env/*env; do
    source $envpath
done

log_finish 'Anyenv'
