#!/usr/bin/env bash

VERSIONS=(
    '4.3.0'
)

for version in ${VERSIONS[@]}; do
    if ! has_version ndenv $version; then
        ndenv install $version | log
    fi
done

ndenv global ${VERSIONS[0]} | log

ndenv rehash
