#!/usr/bin/env bash

log_start 'Go get'

get() {
    GO111MODULE=on run go get "$1"
}

if is_dryrun || has go; then
    get github.com/motemen/ghq
    get github.com/pocke/whichpr
    get github.com/ryym/slv
else
    log_error 'Go is not available'
    exit 1
fi

log_finish 'Go get'
