#!/usr/bin/env bash

log_start 'Go get'

get() {
    run go get "$1"
}

if is_dryrun || has go; then
    get github.com/motemen/ghq
    get github.com/peco/peco/cmd/peco
    get github.com/monochromegane/the_platinum_searcher/cmd/pt
else
    log_error 'Go is not available'
    exit 1
fi

log_finish 'Go get'
