#!/usr/bin/env bash

log_start 'npm install (global)'

install() {
    run npm install -g "$1"
}

if is_dryrun || has npm; then
   install typescript
   install typescript-language-server
   install vscode-langservers-extracted
   install yarn
else
    log_error 'npm is not available'
    exit 1
fi

log_finish 'npm install (global)'
