#!/usr/bin/env bash

# http://brew.sh/

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

if is_dryrun || has ruby; then
    log_info "Installing Homebrew..."
    run ruby -e "\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    log_error 'Ruby is required to install Homebrew'
    exit 1
fi
