#!/usr/bin/env bash

# Install libraries for macOS.

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

log_start "Install for macOS"

mkdir -p "$HOME/local/bin"

if ! has brew; then
    load os/macos/install-brew
fi

load pkgs/brew/install

load lib/rustup

load langs/install

load pkgs/langs/install

if [ ${SHELL##*/} != 'zsh' ]; then
    run ch-sh zsh
fi

log_finish "Install for macOS"
