#!/usr/bin/env bash

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

log_start 'pacman'

install() {
    run sudo pacman --noconfirm -S "$@"
}

if is_dryrun || has pacman; then
    # Note that this needs interactive inputs.
    run sudo pacman -Syu

    # For building AUR packages
    install base-devel

    # Basic development tools
    install alacritty
    install clang
    install docker
    install docker-compose
    install foot
    install fzf
    install ghq
    install git
    install go
    install gvim
    install jq
    install make
    install man-db
    install neovim
    install sudo
    install tailscale
    install tmux
    install tree
    install which
    install zsh

    # For building Ruby 3.2 or later
    install libyaml

    # Utilities
    install iwd
    install pamixer
    install pulseaudio-bluetooth

    # Sway and Wayland
    install blueberry
    install chromium
    install firefox
    install polkit-gnome
    install grim
    install rofi-wayland
    install slurp
    install sway
    install swaybg
    install swayimg
    install wev
    install wl-clipboard
    install wob
    install xorg-xwayland

    # Japanese input
    install fcitx5-im
    install fcitx5-mozc
    install noto-fonts-cjk

    # For running AppImage (https://github.com/AppImage/AppImageKit/wiki/FUSE)
    install fuse2

    # GNOME
    # install gnome

    # AUR
    # https://aur.archlinux.org/packages/slack-desktop
    # https://aur.archlinux.org/packages/gnome-browser-connector-git
else
    log_error 'pacman not found'
    exit 1
fi

log_finish 'pacman'
