#!/bin/zsh

# Aliases
alias ls='ls -F'
alias ll='ls -lF'
alias la='ls -laF'
alias g='git'
alias reload='exec $SHELL -l'
alias v='nvim'
alias vi='vim'
alias ov='vim' # old vim
alias gvi='gvim'
alias nv='nvim'
alias dk='docker'
alias dkc='docker compose'
alias be='bundle exec'
alias npmr='npm run'
alias cg='cargo'
alias manv='() { vim -c "exe \"PluggerLoad man\" | Man $1 | only" }'
alias tf='terraform'
alias y='yarn'
alias k='kubectl'

# For Linux
alias sysu='systemctl --user'
alias journalu='journalctl --user'

command -v xdg-open > /dev/null 2>&1 && alias open='xdg-open'

# We use tmux-256color in tmux but tig does not support it.
# https://github.com/jonas/tig/issues/559
alias tig='TERM=xterm-256color tig'
