#!/bin/zsh

# Aliases
alias ls='ls -F --color=auto'
alias ll='ls -lF --color=auto'
alias la='ls -laF --color=auto'
alias diff='diff --color=auto'
alias g='git'
alias lg='lazygit'
alias reload='exec $SHELL -l'
alias v='nvim'
alias vi='vim'
alias ov='vim' # old vim
alias dk='docker'
alias dkc='docker compose'
alias be='bundle exec'
alias npmr='npm run'
alias cg='cargo'
alias tf='terraform'
alias y='yarn'
alias k='kubectl'
alias h='help'

# For Linux
alias sysu='systemctl --user'
alias journalu='journalctl --user'
command -v xdg-open > /dev/null 2>&1 && alias open='xdg-open'
if command -v wl-copy > /dev/null 2>&1; then
    alias pbcopy='wl-copy'
    alias pbpaste='wl-paste'
fi

# We use tmux-256color in tmux but tig does not support it.
# https://github.com/jonas/tig/issues/559
alias tig='TERM=xterm-256color tig'
