#!/bin/zsh

# Aliases
alias ls='ls -F --color=auto'
alias ll='ls -lhF --color=auto'
alias la='ls -lhaF --color=auto'
alias diff='diff --color=auto'
alias g='git'
alias lg='lazygit'
alias lgp='popup lazygit'
alias reload='exec $SHELL -l'
alias v='nvim'
alias vi='vim'
alias oldv='vim'
alias dk='docker'
alias dkc='docker compose'
alias be='bundle exec'
alias npmr='npm run'
alias cg='cargo'
alias tf='terraform'
alias y='yarn'
alias k='kubectl'
alias h='help'
alias popup='tmux popup -E -d `pwd` -w 90% -h 90%'

# For Linux
alias sysu='systemctl --user'
alias journalu='journalctl --user'
command -v xdg-open > /dev/null 2>&1 && alias open='xdg-open'
