#!/bin/bash

source "$DOTPATH/lib/vitalize.sh"

# Disallow duplicate paths in the '$PATH'.
typeset -U PATH

# Go
export PATH="$GOPATH/bin:$PATH"

export PATH="/usr/sbin:/sbin:$PATH"

if test -f /opt/homebrew/bin/brew; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Homebrew
export PATH="/usr/local/bin:$PATH"

# Deno
export PATH="$HOME/.deno/bin:$PATH"

# Rust
test -f $HOME/.cargo/env && source $HOME/.cargo/env

# Mise
if test -f "$MISE_EXE_PATH"; then
    eval "$($MISE_EXE_PATH activate zsh)"
fi

# Local executables
export PATH="$HOME/.local/bin:$PATH"

# https://specifications.freedesktop.org/basedir-spec/latest/
export XDG_CONFIG_HOME="$HOME/.config"

export EDITOR=nvim

# Define the number of lines of shell prompt (details: "man less").
export LESS_SHELL_LINES=3

# Prevent Homebrew from updating everything when installing a library.
export HOMEBREW_NO_AUTO_UPDATE=1

if command -v bat > /dev/null 2>&1; then
    # Colorize man pages using bat.
    # `col` and `MANROFFORPT` are needed to remove some control chars.
    # `sh` is needed to use pipe. (It seems that macOS can handle it without `sh`, though).
    export MANPAGER="sh -c 'col -bx | bat -l man --style=plain --pager \"toss -F --header 1 --heading ^[A-Z]+\"'"
    export MANROFFOPT="-c"
fi

# A file path for notification handling on AI agent hooks.
# If this file exists, the hook won't send a notification.
# Notification can be annoying when you run an agent non-interactively in a short-running script.
# You can disable the notification like this:
#     # Disable the notification temporarily and enable it again after this script finishes.
#     if [[ -n "$AGENT_NO_NOTIF_PATH" && ! -f "$AGENT_NO_NOTIF_PATH" ]]; then
#         touch "$AGENT_NO_NOTIF_PATH"
#         trap "rm -f $AGENT_NO_NOTIF_PATH" EXIT
#     fi
export AGENT_NO_NOTIF_PATH='/tmp/agent-no-notif'

# Git wrapper.
g() {
case "$1" in
  wti)
    # Go to the specified worktree directory.
    # It cannot be defined as a Git command alias because it cannot change the Git process' cwd.
    local list main dir
    list=$(git worktree list)
    main=$(echo "$list" | head -1)
    main="${main%% *}" # Get the path of the main working tree.
    dir=$(echo "$list" | while IFS= read -r line; do
        local abs="${line%% *}"
        echo "${line/$abs/$(realpath --relative-to="$main" "$abs")}"
    done | fzf --with-nth='{2..} {1}' | awk '{print $1}')
    [ -n "$dir" ] && cd "$main/$dir"
    ;;
  *)
    git "$@"
    ;;
esac
}

# Open a man page in Neovim.
# Tips: you can view the outline of the page by gO.
manv() {
    # Use the slightly reduced column size since Vim usually displays line numbers
    # which makes the available width smaller than the entire terminal width.
    MANWIDTH=$(($(tput cols) - 5)) MANPAGER='nvim +Man!' man "$@"
}

# Print JSON with formatting and colors.
pjson() {
    jq . "$@" | bat --plain -l json
}

chomp() {
    tr -d '\n'
}

workroot() {
    cd "$HOME/ghq/src/github.com/ryym/work"
}
