#!/bin/bash

source "$DOTPATH/lib/vitalize.sh"

# Disallow duplicate paths in the '$PATH'.
typeset -U PATH

# Go
export PATH="$GOPATH/bin:$PATH"

export PATH="/usr/sbin:/sbin:$PATH"

# Homebrew
export PATH="/usr/local/bin:$PATH"

# Deno
export PATH="$HOME/.deno/bin:$PATH"

# Rust
test -f $HOME/.cargo/env && source $HOME/.cargo/env

# Mise
if test -f "$MISE_EXE_PATH"; then
    eval "$($MISE_EXE_PATH activate zsh)"
fi

# Local executables
export PATH="$HOME/local/bin:$PATH"

# https://specifications.freedesktop.org/basedir-spec/latest/
export XDG_CONFIG_HOME="$HOME/.config"

export EDITOR=nvim

# Define the number of lines of shell prompt (details: "man less").
export LESS_SHELL_LINES=3

# Prevent Homebrew from updating everything when installing a library.
export HOMEBREW_NO_AUTO_UPDATE=1

if command -v bat > /dev/null 2>&1; then
    # Colorize man pages using bat.
    # `col` and `MANROFFORPT` are needed to remove some control chars.
    # `sh` is needed to use pipe. (It seems that macOS can handle it without `sh`, though).
    export MANPAGER="sh -c 'col -bx | bat -l man --style=plain'"
    export MANROFFOPT="-c"
fi

# Open a man page in Neovim.
# Tips: you can view the outline of the page by gO.
manv() {
    # Use the slightly reduced column size since Vim usually displays line numbers
    # which makes the available width smaller than the entire terminal width.
    MANWIDTH=$(($(tput cols) - 5)) MANPAGER='nvim +Man!' man "$@"
}
