# Zshenv
# Zsh configuration for non-interactive executions

# Ensure Zsh doesn't load global rc files like '/etc/zprofile'.
unsetopt global_rcs

export DOTPATH=$HOME/.dotfiles

# Load basic environment variables and configure the PATH.
source "$DOTPATH/dotfiles/shell/baseenv"

# Load the local settings.
[ -f ~/.zshenv.local ] && source ~/.zshenv.local
