#!/usr/bin/env bash

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

log_start 'Homebrew bundle'

if is_dryrun || has brew; then
    run brew update

    if ! is_dryrun && [ ! $(brew tap | grep 'homebrew/bundle') ]; then
        run brew tap homebrew/bundle
    fi

    run brew bundle --file="$DOTPATH/sync/pkgs/brew/Brewfile"
else
    log_error 'Homebrew is not installed'
    exit 1
fi

log_finish 'Homebrew bundle'
