#!/usr/bin/env bash

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

if ! has brew; then
    load os/osx/install-brew
fi

load pm/brew/install

load env/install

load pm/lang/install

ch-sh zsh

echo 'Completed. Please restart your shell.'
