#!/usr/bin/env bash

# Check if all dotfiles listed in the 'link_table' exist.

set -eu
trap 'echo LINK STOPPED: $0:$LINENO' ERR INT

DOTPATH="$(cd "$(dirname "$0")/.."; pwd)"

source "$DOTPATH/link/link_table"

for link in "${LINKS[@]}"; do
    srcpath="$DOTPATH/dotfiles/${link%%:*}"

    if [ ! -e "$srcpath" ]; then
        echo "$srcpath doesn't exist." >&2
        exit 1
    fi
done

echo "All dotfile paths are valid."
