#!/usr/bin/env bash

# Create symbolic links of dotfiles in the '$HOME' directory.

set -eu
trap 'echo LINK STOPPED: $0:$LINENO' ERR INT

DOTPATH="$(cd "$(dirname "$0")/.."; pwd)"

source "$DOTPATH/link/link_table"

while getopts t opt
do
    case $opt in
        t) readonly DRY_RUN=1
            ;;
    esac
done

# Check if the dotfiles can be linked.
validate() {
    if [ ! -e "$srcpath" ]; then
        echo "$srcpath doesn't exist." >&2
        exit 1
    fi

    if [ -e "$destpath" ] && [ ! -L "$destpath" ]; then
        echo "$destpath exists but is not a symlnk." >&2
        exit 1
    fi
}

# Create or update symbolic links in $HOME.
link_dotfile() {
    ln -nsf "$srcpath" "$destpath"
    echo "-- $dotfile is linked. --"
}

for link in "${LINKS[@]}"; do
    dotfile="${link#*:}"
    destpath="$HOME/$dotfile"
    srcpath="$DOTPATH/dotfiles/${link%%:*}"

    if [ ${DRY_RUN:-0} -eq 0 ]; then
        validate && link_dotfile
    else
        validate
    fi
done

