#!/usr/bin/env bash

# Create symbolic links of dotfiles.

set -eu
trap 'echo LINK STOPPED: $0:$LINENO' ERR INT

DOTPATH="$(cd "$(dirname "$0")/.."; pwd)"

source "$DOTPATH/link/link_table"

# Check if the dotfiles can be linked.
validate() {
    if [ ! -e "$srcpath" ]; then
        echo "$srcpath doesn't exist." >&2
        exit 1
    fi

    if [ -e "$destpath" ] && [ ! -L "$destpath" ]; then
        echo "$destpath exists but is not a symlnk." >&2
        exit 1
    fi
}

# Create or update symbolic links in $HOME.
link_dotfile() {
    mkdir -p $(dirname "$destpath")
    ln -nsf "$srcpath" "$destpath"
    echo "-- $dotfile is linked. --"
}

for link in "${LINKS[@]}"; do
    dotfile="${link#*:}"
    srcpath="$DOTPATH/dotfiles/${link%%:*}"

    case $dotfile in
        /*) destpath="$dotfile" ;;
        *) destpath="$HOME/$dotfile" ;;
    esac

    if [ ${DOTFILES_DRYRUN:-0} -eq 0 ]; then
        validate && link_dotfile
    else
        validate
    fi
done

