#!/usr/bin/env bash

# Create symbolic links of dotfiles.

set -eu
trap 'echo LINK STOPPED: $0:$LINENO' ERR INT

DOTPATH="$(cd "$(dirname "$0")/.."; pwd)"

source "$DOTPATH/link/link_table"

check_srcpath_exists() {
    if [ ! -e "$srcpath" ]; then
        echo "$srcpath doesn't exist." >&2
        exit 1
    fi
}

check_destpath_is_linkable() {
    if [ -e "$destpath" ] && [ ! -L "$destpath" ]; then
        echo "$destpath exists but is not a symlnk." >&2
        exit 1
    fi
}

# Create or update symbolic links in $HOME.
link_dotfile() {
    case "$srcpath" in
        *.service)
            user=$($sudo && echo '' || echo '--user')
            cmd="systemctl $user link $srcpath"
            ;;
        *)
            cmd="ln -nsf $srcpath $destpath"
            ;;
    esac

    sudo=$($sudo && echo 'sudo' || echo '')
    $sudo mkdir -p $(dirname "$destpath")
    $sudo $cmd
    echo "-- $dotfile is linked. --"
}

for link in "${LINKS[@]}"; do
    head="${link%%:*}"
    if [ "$head" == '!sudo' ]; then
        link="${link#*:}"
        sudo=true
    else
        sudo=false
    fi

    dotfile="${link#*:}"
    srcpath="$DOTPATH/dotfiles/${link%%:*}"

    case "$dotfile" in
        /*) destpath="$dotfile" ;;
        *) destpath="$HOME/$dotfile" ;;
    esac

    if [ ${DOTFILES_LINKTEST:-0} -eq 1 ]; then 
        check_srcpath_exists
    elif [ ${DOTFILES_DRYRUN:-0} -ne 0 ]; then
        check_srcpath_exists && check_destpath_is_linkable
    else
        check_srcpath_exists && check_destpath_is_linkable && link_dotfile
    fi
done
