#!/usr/bin/env bash

source "$DOTPATH/lib/vitalize.sh"

# The files to be linked.
LINKS=(
    'ruby/gemrc:.gemrc'
    'ruby/pryrc:.pryrc'
    'zsh/zshrc:.zshrc'
    'zsh/zshenv:.zshenv'
    'git/gitconfig:.gitconfig'
    'vim:.vim'
    'vim:.config/nvim'
    'cvimrc:.cvimrc'
    'tridactylrc:.tridactylrc'
    'tridactylrc.js:.tridactylrc.js'
    'tmux/tmux.conf:.tmux.conf'
    'tmux:.tmux'
    'ctags:.ctags'
    'prettierrc.json:.prettierrc'
)

case $(ostype) in
    arch)
        LINKS+=(
            'arch/xremap.yml:.config/xremap.yml'
            'arch/xremap.service:.config/systemd/user/xremap.service'
            '!sudo:arch/xremap-udev.rules:/etc/udev/rules.d/00-xremap-udev.rules'
        )
        ;;
esac
