#!/usr/bin/env bash

# The files to be linked.
LINKS=(
    'ruby/pryrc:.pryrc'
    'zsh/zshrc:.zshrc'
    'zsh/zshenv:.zshenv'
    'git/gitconfig:.gitconfig'
    'vim:.vim'
    'vimperatorrc:.vimperatorrc'
    'tmux/tmux.conf:.tmux.conf'
    'tmux:.tmux'
    'ctags:.ctags'
)
