#!/usr/bin/env bash

set -eu
trap 'echo LINK STOPPED: $0:$LINENO' ERR INT

DOTPATH="$(cd "$(dirname "$0")/.."; pwd)"

source "$DOTPATH/link/link_table"
source "$DOTPATH/link/helper.sh"

validate() {
    if [ -e "$destpath" ] && [ ! -L "$destpath" ]; then
        echo "$destpath exists but is not a symlnk." >&2
        exit 1
    fi
}

unlink_dotfile() {
    case $(dotfile_type "$srcpath") in
        systemd)
            echo "[WARN] unlink of systemd service is not supported: $destpath"
            ;;
        normal)
            if [ -e "$destpath" ]; then
                local prefix=$($sudo && echo 'sudo' || echo '')
                $prefix rm -f "$destpath"
                echo "-- $destpath is removed. --"
            fi
            ;;
    esac
}

for link in "${LINKS[@]}"; do
    prepare_variables "$link"
    validate && unlink_dotfile
done

