
if has('vim_starting')
  set columns =999
  set lines   =999

  " Gui font
  if g:is_windows
    set guifont=Consolas:h9:cSHIFTJIS
  elseif g:is_mac
    set guifont=Ricty\ Diminished\ Regular:h14
  endif
endif

if g:is_mac
  set transparency =8
endif

" IM settings {{{
"
if g:is_mac
  " In OSX, noimdisable doesn't work correctly.
  set imdisable
endif

if g:is_windows
  set noimdisable
endif

if has('multi_byte_ime') || has('xim')
  highlight CursorIM guibg=Purple guifg=NONE
  set iminsert=0 imsearch=0
endif

" }}}
