"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" vimrc
"""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Skip initialization if '+eval' feature is disabled {{{
" Note: (see: :help no-eval-feature)
"   In '-eval' environment, the argument of 'if' (including '| endif')
"   is ignored. So all lines after 'if' are ignored too. But
"   backslashes of line-continuation are still recognized and
"   cause errors when 'compatible' option is set. So
"   setting 'cpoptions' to enable line-continuation before
"   'if' statement makes sure all lines get ignored without error.
" }}}
set cpoptions-=C | if 0 | endif

call my#init#setup()

call my#init#colorscheme#setup()

call my#init#commands#setup()

call my#init#options#setup()

call my#init#autocmds#setup()

call my#init#mappings#setup()

function! s:load_init_plug(name) abort
  execute 'packadd' a:name

  let docdir = $MYVIMDIR . '/pack/init/opt/' . a:name . '/doc'
  if isdirectory(docdir)
    execute 'helptags' docdir
  endif
endfunction

" Plugins {{{1

" Loading plugins asynchronously redraws a screen soon
" so suppress the welcome message which disappears by the redrawing.
set shortmess=I

call s:load_init_plug('vim-plugger')

if !$VIM_NO_PLUG
  call plugger#enable({
    \   'conf_root': $MYVIMDIR . '/autoload/my/plug/',
    \   'autoload_prefix': 'my#plug#',
    \ })
endif

runtime macros/matchit.vim



" Local settings {{{1

if filereadable($VIMLOCAL . '/vimrc')
  source $VIMLOCAL/vimrc
  command! Evl edit $VIMLOCAL/vimrc
endif

" }}}

" vim: expandtab softtabstop=2 shiftwidth=2 foldmethod=marker
