#!/usr/bin/env bash

log_start 'Rust cargo'

install() {
    run cargo install "$1"
}

if is_dryrun || has cargo; then
    install bat
    install fd-find
    install ripgrep
    install hgrep
    install git-delta

    case $(ostype) in
        arch)
            # Xremap have to be installed per feature, so we put it into local/bin.
            run cargo install --root "$HOME/local" xremap --features wlroots
            mv "$HOME/local/bin/xremap" "$HOME/local/bin/xremap-wlroots"
            ;;
    esac
else
    log_error 'Rust is not available'
    exit 1
fi

log_finish 'Rust cargo'
