#!/usr/bin/env bash

log_start 'Rust cargo'

install() {
    run cargo install "$1"
}

if is_dryrun || has cargo; then
    install bat
    install fd-find
    install ripgrep
    install hgrep
    install git-delta
else
    log_error 'Rust is not available'
    exit 1
fi

log_finish 'Rust cargo'
