#!/bin/zsh

# Aliases
alias ls='ls -F'
alias ll='ls -lF'
alias la='ls -laF'
alias g='git'
alias reload='exec $SHELL -l'
alias v='vim'
alias vi='vim'
alias gvi='gvim'
alias dk='docker'
alias dkc='docker compose'
alias be='bundle exec'
alias npmr='npm run'
alias cg='cargo'
alias manv='() { vim -c "exe \"PluggerLoad man\" | Man $1 | only" }'
alias tf='terraform'
alias y='yarn'
