
# Ensure Zsh doesn't load global rc files like '/etc/zprofile'.
setopt no_global_rcs

# Disallow duplicate paths in the '$PATH'.
typeset -U PATH

export DOTPATH=$HOME/.dotfiles
source "$DOTPATH/lib/vitalize.sh"

# Homebrew
export PATH="/usr/local/bin:$PATH"

# Anyenv
if [ -d "$ANYENV_PATH" ]; then
    export PATH="$ANYENV_PATH/bin:$PATH"
    eval "$(anyenv init - zsh)"
fi

# Go
export PATH="$PATH:$GOPATH/bin"

# Node modules
export PATH="$PATH:./node_modules/.bin"

# Load the local settings.
[ -f ~/.zshenv.local ] && source ~/.zshenv.local
