
export DOTPATH=$HOME/.dotfiles
source "$DOTPATH/lib/vitalize.sh"

# Ensure Zsh doesn't load global rc files like '/etc/zprofile'.
setopt no_global_rcs

# Disallow duplicate paths in the '$PATH'.
typeset -U PATH

# Go
export PATH="$GOPATH/bin:$PATH"

export PATH="/usr/sbin:/sbin:$PATH"

# Homebrew
export PATH="/usr/local/bin:$PATH"

# Anyenv
if [ -d "$ANYENV_PATH" ]; then
    export PATH="$ANYENV_PATH/bin:$PATH"
    eval "$(anyenv init - zsh)"
fi

# added by travis gem
[ -f /Users/ryu/.travis/travis.sh ] && source /Users/ryu/.travis/travis.sh

# Rust
[ -f $HOME/.cargo/env ] && source $HOME/.cargo/env

# Load the local settings.
[ -f ~/.zshenv.local ] && source ~/.zshenv.local
