# ZSHRC
# man zsh

export LANG=en_US.UTF-8
export LESS='-R'

bindkey -e # Like Emacs.

# Remap <C-w> to <C-t> to use <C-w> for window switching in Vim terminal.
bindkey "^t" backward-kill-word

autoload -Uz colors
colors

autoload -U compinit
compinit

# Use completion with case-insensitivity.
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# Histories
HISTFILE=~/.zsh_history
HISTSIZE=500000 # メモリにロードされる件数(検索できる)
SAVEHIST=500000 # $HISTFILEに保存される件数

# History searching
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

# vcs_info
autoload -Uz vcs_info
autoload -Uz add-zsh-hook
zstyle ':vcs_info:*' formats '%F{blue}(%b)%f'
zstyle ':vcs_info:*' actionformats '%F{red}(%b|%a)%f'

function _update_prompt() {
    LANG=en_US.UTF-8 vcs_info
    ssh_info=$(test -z "$SSH_CLIENT" && echo '' || echo '(SSH)')
    PROMPT="%{${fg[green]}%}[%n@%m]%{${fg[red]%}$ssh_info ${vcs_info_msg_0_}%{${reset_color}%} %~
%# "
}
add-zsh-hook precmd _update_prompt

setopt hist_ignore_dups
setopt share_history

# Options

setopt auto_cd
setopt auto_pushd

setopt nocorrect
setopt list_packed
setopt nolistbeep

unsetopt nomatch

# Aliases
source "$DOTPATH/dotfiles/zsh/aliases"

## FZF
export FZF_DEFAULT_OPTS="-i --cycle --reverse --bind=ctrl-k:kill-line,ctrl-s:select-all,ctrl-d:deselect-all"

# Make fzf super faster
# - https://github.com/junegunn/fzf#respecting-gitignore
# - https://github.com/sharkdp/fd
export FZF_DEFAULT_COMMAND="fd --hidden --no-ignore"

# http://qiita.com/strsk/items/9151cef7e68f0746820d
# http://qiita.com/udzura/items/3f120b5e4733fe85078d
function fzf-src() {
    local selected_dir=$(eval "$1" | fzf --query "$LBUFFER")
    if [ -n "$selected_dir" ]; then
        BUFFER="cd ${selected_dir}"
        zle accept-line
    fi
    zle clear-screen
}

function fzf-ghq() {
    fzf-src 'ghq list -p'
}
zle -N fzf-ghq
bindkey '^]' fzf-ghq
bindkey '^g' fzf-ghq

# https://github.com/rhysd/hgrep
function hgrep() {
    command hgrep --term-width "$COLUMNS" "$@"
}

# https://github.com/direnv/direnv
if has direnv; then
    eval "$(direnv hook zsh)"
fi

# AWS-CLI
# which aws_zsh_completer >/dev/null 2>&1 && $(which aws_zsh_completer.sh)

# Load local settings.
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
