#!/usr/bin/env bash

# Install libraries for CachyOS.

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

log_start "Install for CachyOS"

mkdir -p "$HOME/local/bin"

load pkgs/pacman/install

load lib/rustup

load langs/install

load pkgs/langs/install

if [ ${SHELL##*/} != 'zsh' ]; then
    run ch-sh zsh
fi

log_finish "Install for CachyOS"
