# https://sw.kovidgoyal.net/kitty/conf/

# shell /bin/zsh --login -c tmux

# === font ===

# Set in the local config.
# font_family Intel One Mono
# font_size 11.0

# === key bindings ===

# clear_all_shortcuts yes

map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard

# Remap navigation keys to ensure consistent behavior across applications.
# See ryym/dotfiles/xremap/README.md for details.

# Ctrl-a
map home        send_text all \x01
# Ctrl-e
map end         send_text all \x05
# Ctrl-k
map shift+end   send_text all \x0b
map delete      discard_event
# Ctrl-n
map ctrl+down   send_text all \x0e
# Ctrl-p
map ctrl+up     send_text all \x10
# Ctrl-b
map left        send_text all \x02
# Ctrl-f
map right       send_text all \x06

# === styles ===

background_opacity 0.98

# Color theme: https://github.com/sainnhe/everforest
background  #2d353b
foreground  #d3c6aa
# normal
color0  #475258
color1  #e67e80
color2  #a7c080
color3  #dbbc7f
color4  #7fbbb3
color5  #d699b6
color6  #83c092
color7  #d3c6aa
# bright
color8   #475258
color9   #e67e80
color10  #a7c080
color11  #dbbc7f
color12  #7fbbb3
color13  #d699b6
color14  #83c092
color15  #d3c6aa

# === local config ===

# Load local overrides if present.
include ~/.config/kitty/kitty.local.conf
