#!/usr/bin/env bash

# Install libraries which are necessary for development.
# This script detects a current OS automatically and run
# proper installations for the OS.

set -eu
trap 'echo SYNC STOPPED: $0:$LINENO' ERR INT

DOTPATH="$(cd "$(dirname "$0")/.."; pwd)"

source "$DOTPATH/sync/lib/vitalize.sh"

osname=${OS:-$(ostype)}
installer="$DOTPATH/sync/os/$osname/install"

if [ -z $osname ] || [ ! -f $installer ]; then
    log_error 'Sorry, Your OS is not supported'
    exit 1
else
    echo "$(c_blue "$DOTFILES_LOGO")"

    is_dryrun && log_warn "
        ====== DRY RUN ($osname) ======
    "

    log_start "Install"
    log_info "OS: $(c_magenta "$osname")"

    load os/$osname/install

    log_finish "Install"
    log_success "All installations are done successfully!"
    log_warn "To apply changes, you may need to restart your PC."
fi
