#!/usr/bin/env bash

has() {
    which $1 > /dev/null
}

clone_repository() {
    # TODO: Use master branch.
    local repository=https://github.com/ryym/dotfiles
    local archive_url=$repository/archive/sync.tar.gz
    local archive_dest=dotfiles-sync

    # Ensure we can use Git.
    if ! has git; then
        if has apt-get; then
            sudo apt-get update
            sudo apt-get install -y git
        else
            echo 'git is required'
            exit 1
        fi
    fi

    # TODO: Use master branch.
    git clone -b sync $repository $DOTPATH
}

if [ -z "$DOTPATH" ]; then
    DOTPATH=~/.dotfiles
    export DOTPATH
fi

if [ -d "$DOTPATH" ]; then
    echo "$DOTPATH already exists"
    exit 1
fi

clone_repository

# XXX: Should be run by users explicitly.
if [ $? -eq 0 ]; then
    "$DOTPATH/sync/init"
else
    exit 1
fi
