#!/usr/bin/env bash

# Install libraries for Fedora.

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

log_start "Install for Fedora"

mkdir -p "$HOME/local/bin"

load pkgs/dnf/install

load lib/rustup

load lang-envs/install

load pkgs/langs/install

if [ ${SHELL##*/} != 'zsh' ]; then
    run ch-sh zsh
fi

log_finish "Install for Fedora"
