tap 'homebrew/bundle'

brew 'autoconf'
brew 'ctags'
brew 'git'
brew 'haskell-stack'
brew 'heroku'
brew 'hub'
brew 'macvim'
brew 'pkg-config'
brew 'reattach-to-user-namespace'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'zsh'

tap 'caskroom/cask'
brew 'brew-cask'

cask 'alfred'
cask 'appcleaner'
cask 'caffeine'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'karabiner'
cask 'skitch'
cask 'skim'
cask 'slack'
cask 'vagrant'
cask 'virtualbox'
# cask 'mactex'  # It takes a hell of a time..

tap 'caskroom/fonts'

cask 'font-ricty-diminished'

