#!/usr/bin/env bash

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

log_start 'Homebrew bundle'

if ! has brew; then
    log_error 'Homebrew is not installed'
    exit 1
else
    run brew update

    if [ ! $(brew tap | grep 'homebrew/bundle') ]; then
        run brew tap homebrew/bundle
    fi

    run brew bundle --file="$DOTPATH/sync/pm/brew/Brewfile"
fi

log_finish 'Homebrew bundle'
