#!/usr/bin/env bash

log_start 'Rubygems'

install() {
    log_info "Installing gem $(c_magenta $1)..."
    gem install $1 | log
}

if has gem; then
    install bundle
    install pry
    install byebug
else
    log_error 'gem command is not available'
    exit 1
fi

log_finish 'Rubygems'
