#!/usr/bin/env bash

log_start 'Rubygems'

install() {
    run gem install $1
}

if is_dryrun || has gem; then
    install bundle
    install pry
    install byebug
else
    log_error 'gem command is not available'
    exit 1
fi

log_finish 'Rubygems'
