#!/usr/bin/env bash

VERSIONS=(
    '3.7.3'
)

set +u

# https://github.com/jiansoung/issues-list/issues/13#issuecomment-470275744
LDFLAGS="${LDFLAGS} -L/usr/local/opt/zlib/lib"
CPPFLAGS="${CPPFLAGS} -I/usr/local/opt/zlib/include"
LDFLAGS="${LDFLAGS} -L/usr/local/opt/sqlite/lib"
CPPFLAGS="${CPPFLAGS} -I/usr/local/opt/sqlite/include"
PKG_CONFIG_PATH="${PKG_CONFIG_PATH} /usr/local/opt/zlib/lib/pkgconfig"
PKG_CONFIG_PATH="${PKG_CONFIG_PATH} /usr/local/opt/sqlite/lib/pkgconfig"

set -u

# FIXME: Pyenv seems not support M1 Mac yet.

# for version in ${VERSIONS[@]}; do
#     install_version pyenv $version
# done

# set_global_version pyenv ${VERSIONS[0]}
