#!/usr/bin/env bash

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/helper.sh"

load env/install

load pm/apt-get/install

load pm/lang/install

ch-sh zsh

echo 'Completed. Please restart your shell.'

