#!/usr/bin/env bash

set -eu
trap 'echo SYNC STOPPED: $0' ERR INT
source "$DOTPATH/sync/lib/vitalize.sh"

load pm/apt-get/install

load env/install

load pm/lang/install

ch-sh zsh

echo 'Completed. Please restart your shell.'

